---
apiVersion: v1
kind: Service
metadata:
  name: generate-znc-cert
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: generate-znc-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generate-znc-cert
spec:
  selector:
    matchLabels:
      app: generate-znc-cert
  replicas: 1
  template:
    metadata:
      labels:
        app: generate-znc-cert
    spec:
      restartPolicy: Never
      containers:
      - name: generate-znc-cert
        image: yitsushi/znc-certbot:latest
        env:
          - name: EMAIL
            value: "efertone@pm.me"
          - name: DOMAIN
            value: "master.code-infection.com"
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: generate-znc-cert-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: master.code-infection.com
    http:
      paths:
      - backend:
          serviceName: generate-znc-cert
          servicePort: 80
